In [1]:
# Following Topics are covered in this note

# Creating DataFrame
# Rows and Column operation
# Indexing

In [3]:
import pandas as pd

In [4]:
#Creating a dictionary object
weatherData={
    'Date':['1/1/2019','1/2/2019','1/3/2019','1/4/2019'],
    'Temperature':['36','37','38','39'],
    'Windspeed':['1','3','7','9'],
    'Event':['Rain','Sunny','Cloudy','Snow']
}

In [7]:
# Use below command to transform into Dataframe 
df1=pd.DataFrame(weatherData)
df1[['Event','Temperature']]

    Event Temperature
0    Rain          36
1   Sunny          37
2  Cloudy          38
3    Snow          39

In [8]:
rows, columns = df1.shape
print(rows)
print(columns)

4
4

In [9]:
df1

       Date Temperature Windspeed   Event
0  1/1/2019          36         1    Rain
1  1/2/2019          37         3   Sunny
2  1/3/2019          38         7  Cloudy
3  1/4/2019          39         9    Snow

In [12]:
df1[1:2][['Windspeed']]

  Windspeed
1         3

In [13]:
# Reading csv using read csv command directly
df2=pd.read_csv("district_wise_rainfall_normal.csv")

In [14]:
# To get the dimensions(No of Rows & No of Columns) of DataFrame use following command, Output is a tuple
df2.shape

(640, 19)

In [15]:
# If we wish to store rows and columns do following way.
rows,columns=df2.shape

In [16]:
rows

640

In [17]:
columns

19

In [18]:
# If we want to print only initial few rows in data frame use following command
df2.head()

,STATE/UT,DISTRICT,JAN,FEB,MAR,APR,MAY,JUN,JUL,AUG,SEP,OCT,NOV,DEC,ANNUAL,JAN+FEB,MAM,JJAS,OND
0,ANDAMAN And NICOBAR ISLANDS,NICOBAR,107.3,57.9,65.2,117.0,358.5,295.5,285.0,271.9,354.8,326.0,315.2,250.9,2805.2,165.2,540.7,1207.2,892.1
1,ANDAMAN And NICOBAR ISLANDS,SOUTH ANDAMAN,43.7,26.0,18.6,90.5,374.4,457.2,421.3,423.1,455.6,301.2,275.8,128.3,3015.7,69.7,483.5,1757.2,705.3
2,ANDAMAN And NICOBAR ISLANDS,N & M ANDAMAN,32.7,15.9,8.6,53.4,343.6,503.3,465.4,460.9,454.8,276.1,198.6,100.0,2913.3,48.6,405.6,1884.4,574.7
3,ARUNACHAL PRADESH,LOHIT,42.2,80.8,176.4,358.5,306.4,447.0,660.1,427.8,313.6,167.1,34.1,29.8,3043.8,123.0,841.3,1848.5,231.0
4,ARUNACHAL PRADESH,EAST SIANG,33.3,79.5,105.9,216.5,323.0,738.3,990.9,711.2,568.0,206.9,29.5,31.7,4034.7,112.8,645.4,3008.4,268.1

In [19]:
# If we want to print only last few rows in data frame use following command
df2.tail()

,STATE/UT,DISTRICT,JAN,FEB,MAR,APR,MAY,JUN,JUL,AUG,SEP,OCT,NOV,DEC,ANNUAL,JAN+FEB,MAM,JJAS,OND
635,KERALA,THIRUVANANTHA,19.3,21.1,35.5,116.7,216.6,338.7,228.9,142.0,161.7,268.0,192.0,62.7,1803.2,40.4,368.8,871.3,522.7
636,KERALA,IDUKKI,13.4,22.1,43.6,150.4,232.6,651.6,788.9,527.3,308.4,343.2,172.9,48.1,3302.5,35.5,426.6,2276.2,564.2
637,KERALA,KASARGOD,2.3,1.0,8.4,46.9,217.6,999.6,1108.5,636.3,263.1,234.9,84.6,18.4,3621.6,3.3,272.9,3007.5,337.9
638,KERALA,PATHANAMTHITTA,19.8,45.2,73.9,184.9,294.7,556.9,539.9,352.7,266.2,359.4,213.5,51.3,2958.4,65.0,553.5,1715.7,624.2
639,KERALA,WAYANAD,4.8,8.3,17.5,83.3,174.6,698.1,1110.4,592.9,230.7,213.1,93.6,25.8,3253.1,13.1,275.4,2632.1,332.5

In [20]:
# If we want to print certain no.of initial rows or last rows use following command

df2.head(10)
df2.tail(10)

,STATE/UT,DISTRICT,JAN,FEB,MAR,APR,MAY,JUN,JUL,AUG,SEP,OCT,NOV,DEC,ANNUAL,JAN+FEB,MAM,JJAS,OND
630,KERALA,KOZHIKODE,2.3,3.9,15.1,80.9,256.6,895.8,955.2,500.9,251.2,262.1,130.1,30.0,3384.1,6.2,352.6,2603.1,422.2
631,KERALA,MALAPPURAM,1.7,3.9,12.7,86.8,221.3,660.9,792.9,395.3,211.3,290.4,135.1,22.8,2835.1,5.6,320.8,2060.4,448.3
632,KERALA,PALAKKAD,2.9,6.5,22.5,98.7,158.7,464.3,595.4,333.8,179.2,263.8,138.6,25.6,2290.0,9.4,279.9,1572.7,428.0
633,KERALA,KOLLAM,17.5,33.7,62.6,158.5,248.5,457.7,398.0,258.7,217.9,362.7,221.4,54.5,2491.7,51.2,469.6,1332.3,638.6
634,KERALA,THRISSUR,3.4,7.5,17.0,79.2,289.1,707.4,772.9,440.1,277.1,296.3,138.1,35.0,3063.1,10.9,385.3,2197.5,469.4
635,KERALA,THIRUVANANTHA,19.3,21.1,35.5,116.7,216.6,338.7,228.9,142.0,161.7,268.0,192.0,62.7,1803.2,40.4,368.8,871.3,522.7
636,KERALA,IDUKKI,13.4,22.1,43.6,150.4,232.6,651.6,788.9,527.3,308.4,343.2,172.9,48.1,3302.5,35.5,426.6,2276.2,564.2
637,KERALA,KASARGOD,2.3,1.0,8.4,46.9,217.6,999.6,1108.5,636.3,263.1,234.9,84.6,18.4,3621.6,3.3,272.9,3007.5,337.9
638,KERALA,PATHANAMTHITTA,19.8,45.2,73.9,184.9,294.7,556.9,539.9,352.7,266.2,359.4,213.5,51.3,2958.4,65.0,553.5,1715.7,624.2
639,KERALA,WAYANAD,4.8,8.3,17.5,83.3,174.6,698.1,1110.4,592.9,230.7,213.1,93.6,25.8,3253.1,13.1,275.4,2632.1,332.5

In [21]:
# Let's say if want to print only from row 2 to 10 use below command (It includes row 2 but not row 10)
df2[2:10]

,STATE/UT,DISTRICT,JAN,FEB,MAR,APR,MAY,JUN,JUL,AUG,SEP,OCT,NOV,DEC,ANNUAL,JAN+FEB,MAM,JJAS,OND
2,ANDAMAN And NICOBAR ISLANDS,N & M ANDAMAN,32.7,15.9,8.6,53.4,343.6,503.3,465.4,460.9,454.8,276.1,198.6,100.0,2913.3,48.6,405.6,1884.4,574.7
3,ARUNACHAL PRADESH,LOHIT,42.2,80.8,176.4,358.5,306.4,447.0,660.1,427.8,313.6,167.1,34.1,29.8,3043.8,123.0,841.3,1848.5,231.0
4,ARUNACHAL PRADESH,EAST SIANG,33.3,79.5,105.9,216.5,323.0,738.3,990.9,711.2,568.0,206.9,29.5,31.7,4034.7,112.8,645.4,3008.4,268.1
5,ARUNACHAL PRADESH,SUBANSIRI F.D,28.0,48.3,85.3,101.5,140.5,228.4,217.4,182.8,159.8,75.9,20.9,11.6,1300.4,76.3,327.3,788.4,108.4
6,ARUNACHAL PRADESH,TIRAP,42.2,72.7,141.0,316.9,328.7,614.7,851.9,500.6,418.3,218.7,42.9,22.9,3571.5,114.9,786.6,2385.5,284.5
7,ARUNACHAL PRADESH,ANJAW (LOHIT),42.2,80.8,176.4,358.5,306.4,447.0,660.1,427.8,313.6,167.1,34.1,29.8,3043.8,123.0,841.3,1848.5,231.0
8,ARUNACHAL PRADESH,LOWER DIBANG,83.7,153.9,303.5,383.6,268.0,374.2,272.0,160.5,266.7,167.2,64.0,56.0,2553.3,237.6,955.1,1073.4,287.2
9,ARUNACHAL PRADESH,CHANGLANG,70.3,170.9,367.9,554.4,334.2,526.2,460.8,291.5,353.6,275.0,64.9,74.2,3543.9,241.2,1256.5,1632.1,414.1

In [22]:
#If want to print everything follow as below
df2[:] 
#(or) 
df2

,STATE/UT,DISTRICT,JAN,FEB,MAR,APR,MAY,JUN,JUL,AUG,SEP,OCT,NOV,DEC,ANNUAL,JAN+FEB,MAM,JJAS,OND
0,ANDAMAN And NICOBAR ISLANDS,NICOBAR,107.3,57.9,65.2,117.0,358.5,295.5,285.0,271.9,354.8,326.0,315.2,250.9,2805.2,165.2,540.7,1207.2,892.1
1,ANDAMAN And NICOBAR ISLANDS,SOUTH ANDAMAN,43.7,26.0,18.6,90.5,374.4,457.2,421.3,423.1,455.6,301.2,275.8,128.3,3015.7,69.7,483.5,1757.2,705.3
2,ANDAMAN And NICOBAR ISLANDS,N & M ANDAMAN,32.7,15.9,8.6,53.4,343.6,503.3,465.4,460.9,454.8,276.1,198.6,100.0,2913.3,48.6,405.6,1884.4,574.7
3,ARUNACHAL PRADESH,LOHIT,42.2,80.8,176.4,358.5,306.4,447.0,660.1,427.8,313.6,167.1,34.1,29.8,3043.8,123.0,841.3,1848.5,231.0
4,ARUNACHAL PRADESH,EAST SIANG,33.3,79.5,105.9,216.5,323.0,738.3,990.9,711.2,568.0,206.9,29.5,31.7,4034.7,112.8,645.4,3008.4,268.1
5,ARUNACHAL PRADESH,SUBANSIRI F.D,28.0,48.3,85.3,101.5,140.5,228.4,217.4,182.8,159.8,75.9,20.9,11.6,1300.4,76.3,327.3,788.4,108.4
6,ARUNACHAL PRADESH,TIRAP,42.2,72.7,141.0,316.9,328.7,614.7,851.9,500.6,418.3,218.7,42.9,22.9,3571.5,114.9,786.6,2385.5,284.5
7,ARUNACHAL PRADESH,ANJAW (LOHIT),42.2,80.8,176.4,358.5,306.4,447.0,660.1,427.8,313.6,167.1,34.1,29.8,3043.8,123.0,841.3,1848.5,231.0
8,ARUNACHAL PRADESH,LOWER DIBANG,83.7,153.9,303.5,383.6,268.0,374.2,272.0,160.5,266.7,167.2,64.0,56.0,2553.3,237.6,955.1,1073.4,287.2
9,ARUNACHAL PRADESH,CHANGLANG,70.3,170.9,367.9,554.4,334.2,526.2,460.8,291.5,353.6,275.0,64.9,74.2,3543.9,241.2,1256.5,1632.1,414.1
10,ARUNACHAL PRADESH,PAPUM PARE,33.5,67.8,106.1,226.9,453.0,640.5,609.5,503.4,492.3,214.7,19.2,11.3,3378.2,101.3,786.0,2245.7,245.2
11,ARUNACHAL PRADESH,LOW SUBANSIRI,97.5,109.3,92.4,204.3,266.2,284.1,248.9,270.5,192.7,78.5,49.5,27.2,1921.1,206.8,562.9,996.2,155.2
12,ARUNACHAL PRADESH,UPPER SIANG,74.3,176.7,362.6,397.5,408.7,801.9,653.0,417.9,686.0,264.9,86.9,71.7,4402.1,251.0,1168.8,2558.8,423.5
13,ARUNACHAL PRADESH,WEST SIANG,26.0,66.7,76.8,229.2,239.5,416.6,592.4,312.4,291.1,126.8,33.7,29.5,2440.7,92.7,545.5,1612.5,190.0
14,ARUNACHAL PRADESH,DIBANG VALLEY,83.7,153.9,303.5,383.6,268.0,374.2,272.0,160.5,266.7,167.2,64.0,56.0,2553.3,237.6,955.1,1073.4,287.2
15,ARUNACHAL PRADESH,WEST KAMENG,35.2,43.5,58.9,134.3,341.1,665.3,749.9,579.1,490.9,233.9,40.3,27.0,3399.4,78.7,534.3,2485.2,301.2
16,ARUNACHAL PRADESH,EAST KAMENG,49.0,74.4,96.5,156.9,208.0,345.7,368.5,256.2,275.9,138.2,34.4,27.2,2030.9,123.4,461.4,1246.3,199.8
17,ARUNACHAL PRADESH,TAWANG(W KAME,35.2,43.5,58.9,134.3,341.1,665.3,749.9,579.1,490.9,233.9,40.3,27.0,3399.4,78.7,534.3,2485.2,301.2
18,ARUNACHAL PRADESH,KURUNG KUMEY,82.7,70.0,128.2,245.7,271.4,292.7,404.0,276.3,283.5,92.3,32.3,42.4,2221.5,152.7,645.3,1256.5,167.0
19,ASSAM,CACHAR,13.3,50.2,168.3,262.5,386.4,532.1,526.2,470.8,360.8,182.4,34.8,11.4,2999.2,63.5,817.2,1889.9,228.6
20,ASSAM,DARRANG,13.1,21.4,53.5,168.8,320.0,419.7,345.8,272.1,221.5,95.4,17.2,9.3,1957.8,34.5,542.3,1259.1,121.9
21,ASSAM,GOALPARA,12.7,20.4,51.1,196.6,399.8,567.8,502.8,334.6,304.9,157.7,21.7,5.2,2575.3,33.1,647.5,1710.1,184.6
22,ASSAM,KAMRUP,12.0,20.8,58.6,151.7,293.4,365.5,345.1,248.7,188.4,106.6,15.1,7.5,1813.4,32.8,503.7,1147.7,129.2
23,ASSAM,LAKHIMPUR,27.7,48.6,76.7,165.5,331.9,528.3,605.2,467.6,424.1,140.3,23.0,20.4,2859.3,76.3,574.1,2025.2,183.7
24,ASSAM,NORTH CACHAR,16.7,47.5,158.9,207.9,308.0,328.1,270.3,201.3,189.1,196.4,42.1,11.2,1977.5,64.2,674.8,988.8,249.7
25,ASSAM,NAGAON,12.0,22.5,48.1,128.9,171.3,285.9,326.3,294.1,218.6,120.0,21.6,10.8,1660.1,34.5,348.3,1124.9,152.4
26,ASSAM,SIVASAGAR,20.1,33.2,78.3,126.5,257.1,255.5,374.8,342.3,196.9,96.3,20.3,10.3,1811.6,53.3,461.9,1169.5,126.9
27,ASSAM,BARPETA,10.3,26.9,54.0,175.7,391.5,694.3,757.3,527.3,462.1,142.1,20.4,12.7,3274.6,37.2,621.2,2441.0,175.2
28,ASSAM,DHUBRI,10.3,11.7,46.6,147.5,391.6,603.0,554.7,418.7,340.1,155.1,19.2,4.1,2702.6,22.0,585.7,1916.5,178.4
29,ASSAM,DIBRUGARH,30.6,53.1,119.8,229.9,292.4,401.0,519.4,405.1,325.9,136.9,24.0,18.5,2556.6,83.7,642.1,1651.4,179.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
610,KARNATAKA,BANGALORE RUR,1.7,5.8,7.6,36.2,93.1,71.2,91.7,118.1,170.9,171.8,55.4,13.5,837.0,7.5,136.9,451.9,240.7
611,KARNATAKA,BELLARY,1.4,1.4,2.9,26.2,57.9,72.4,77.0,89.3,137.3,116.3,31.1,9.6,622.8,2.8,87.0,376.0,157.0
612,KARNATAKA,CHIKMAGALUR,1.6,2.0,12.0,60.2,105.9,395.0,662.1,425.0,175.2,167.4,58.8,12.3,2077.5,3.6,178.1,1657.3,238.5
613,KARNATAKA,CHITRADURGA,1.4,1.2,4.4,25.8,64.9,50.5,56.1,58.9,105.5,116.4,33.8,8.8,527.7,2.6,95.1,271.0,159.0
614,KARNATAKA,KODAGU,3.5,4.2,18.5,89.8,152.7,542.2,884.4,543.9,211.4,201.7,71.6,17.5,2741.4,7.7,261.0,2181.9,290.8
615,KARNATAKA,HASSAN,1.3,2.5,10.7,55.1,102.2,125.0,203.8,130.0,115.5,156.0,54.1,10.9,967.1,3.8,168.0,574.3,221.0
616,KARNATAKA,KOLAR,2.7,4.5,10.4,27.8,74.4,63.3,76.4,91.2,151.8,148.2,58.8,21.6,731.1,7.2,112.6,382.7,228.6
617,KARNATAKA,MANDYA,1.9,3.6,7.6,45.3,105.1,48.7,49.3,58.9,128.2,153.1,47.0,14.0,662.7,5.5,158.0,285.1,214.1
618,KARNATAKA,MYSORE,2.5,3.5,11.4,58.7,124.6,79.7,92.4,64.8,106.7,152.4,48.8,13.1,758.6,6.0,194.7,343.6,214.3
619,KARNATAKA,SHIMOGA,0.5,0.4,6.3,38.0,78.3,346.8,624.3,403.8,139.1,137.5,44.6,8.3,1827.9,0.9,122.6,1514.0,190.4
620,KARNATAKA,TUMKUR,2.4,3.0,7.1,34.0,87.1,61.5,69.7,79.5,148.5,148.9,46.7,10.1,698.5,5.4,128.2,359.2,205.7
621,KARNATAKA,BANGALORE URB,2.3,6.7,8.2,39.2,106.3,73.9,91.6,128.9,181.3,159.7,53.9,18.0,870.0,9.0,153.7,475.7,231.6
622,KARNATAKA,CHAMARAJANAGA,3.4,6.0,13.2,69.2,131.2,61.8,68.7,66.0,124.1,157.8,62.7,24.3,788.4,9.4,213.6,320.6,244.8
623,KARNATAKA,DAVANGERE,1.1,0.8,4.2,35.0,74.0,78.7,102.9,87.0,116.3,124.4,44.9,7.4,676.7,1.9,113.2,384.9,176.7
624,KARNATAKA,RAMNAGAR(BNGR),1.5,4.7,10.2,47.9,122.3,73.1,84.5,108.8,187.6,174.1,54.0,15.0,883.7,6.2,180.4,454.0,243.1
625,KARNATAKA,CHICKBALLAPUR,2.1,4.6,8.2,27.2,69.4,64.3,89.2,104.9,153.4,156.8,52.9,15.5,748.5,6.7,104.8,411.8,225.2
626,KERALA,ALAPPUZHA,17.5,27.9,45.1,134.0,298.7,593.0,533.0,343.1,276.8,332.9,187.6,51.6,2841.2,45.4,477.8,1745.9,572.1
627,KERALA,CANNUR,2.5,2.0,7.6,57.9,235.0,852.4,1055.0,540.9,220.7,229.4,91.6,24.1,3319.1,4.5,300.5,2669.0,345.1
628,KERALA,ERNAKULAM,13.2,18.8,31.2,112.0,300.4,696.4,670.2,401.3,297.1,299.9,145.0,44.4,3029.9,32.0,443.6,2065.0,489.3
629,KERALA,KOTTAYAM,13.0,24.9,42.3,136.1,281.8,649.1,591.4,386.0,270.8,316.6,177.4,41.1,2930.5,37.9,460.2,1897.3,535.1
630,KERALA,KOZHIKODE,2.3,3.9,15.1,80.9,256.6,895.8,955.2,500.9,251.2,262.1,130.1,30.0,3384.1,6.2,352.6,2603.1,422.2
631,KERALA,MALAPPURAM,1.7,3.9,12.7,86.8,221.3,660.9,792.9,395.3,211.3,290.4,135.1,22.8,2835.1,5.6,320.8,2060.4,448.3
632,KERALA,PALAKKAD,2.9,6.5,22.5,98.7,158.7,464.3,595.4,333.8,179.2,263.8,138.6,25.6,2290.0,9.4,279.9,1572.7,428.0
633,KERALA,KOLLAM,17.5,33.7,62.6,158.5,248.5,457.7,398.0,258.7,217.9,362.7,221.4,54.5,2491.7,51.2,469.6,1332.3,638.6
634,KERALA,THRISSUR,3.4,7.5,17.0,79.2,289.1,707.4,772.9,440.1,277.1,296.3,138.1,35.0,3063.1,10.9,385.3,2197.5,469.4
635,KERALA,THIRUVANANTHA,19.3,21.1,35.5,116.7,216.6,338.7,228.9,142.0,161.7,268.0,192.0,62.7,1803.2,40.4,368.8,871.3,522.7
636,KERALA,IDUKKI,13.4,22.1,43.6,150.4,232.6,651.6,788.9,527.3,308.4,343.2,172.9,48.1,3302.5,35.5,426.6,2276.2,564.2
637,KERALA,KASARGOD,2.3,1.0,8.4,46.9,217.6,999.6,1108.5,636.3,263.1,234.9,84.6,18.4,3621.6,3.3,272.9,3007.5,337.9
638,KERALA,PATHANAMTHITTA,19.8,45.2,73.9,184.9,294.7,556.9,539.9,352.7,266.2,359.4,213.5,51.3,2958.4,65.0,553.5,1715.7,624.2
639,KERALA,WAYANAD,4.8,8.3,17.5,83.3,174.6,698.1,1110.4,592.9,230.7,213.1,93.6,25.8,3253.1,13.1,275.4,2632.1,332.5

In [29]:
# If we wish to print column names use below command
df2.columns

Index(['STATE/UT', 'DISTRICT', 'JAN', 'FEB', 'MAR', 'APR', 'MAY', 'JUN', 'JUL',
       'AUG', 'SEP', 'OCT', 'NOV', 'DEC', 'ANNUAL', 'JAN+FEB', 'MAM', 'JJAS',
       'OND'],
      dtype='object')

In [19]:
# If we want to print the content of the particular column use following command
df2.DISTRICT 
#(Or)
df2['DISTRICT']

0             NICOBAR
1       SOUTH ANDAMAN
2       N & M ANDAMAN
3               LOHIT
4          EAST SIANG
5       SUBANSIRI F.D
6               TIRAP
7       ANJAW (LOHIT)
8        LOWER DIBANG
9           CHANGLANG
10         PAPUM PARE
11      LOW SUBANSIRI
12        UPPER SIANG
13         WEST SIANG
14      DIBANG VALLEY
15        WEST KAMENG
16        EAST KAMENG
17      TAWANG(W KAME
18       KURUNG KUMEY
19             CACHAR
20            DARRANG
21           GOALPARA
22             KAMRUP
23          LAKHIMPUR
24       NORTH CACHAR
25             NAGAON
26          SIVASAGAR
27            BARPETA
28             DHUBRI
29          DIBRUGARH
            ...
610     BANGALORE RUR
611           BELLARY
612       CHIKMAGALUR
613       CHITRADURGA
614            KODAGU
615            HASSAN
616             KOLAR
617            MANDYA
618            MYSORE
619           SHIMOGA
620            TUMKUR
621     BANGALORE URB
622     CHAMARAJANAGA
623         DAVANGERE
624    RAMNAGAR(BNGR)
625     CHICKBALLAPUR
626         ALAPPUZHA
627            CANNUR
628         ERNAKULAM
629          KOTTAYAM
630         KOZHIKODE
631        MALAPPURAM
632          PALAKKAD
633            KOLLAM
634          THRISSUR
635     THIRUVANANTHA
636            IDUKKI
637          KASARGOD
638    PATHANAMTHITTA
639           WAYANAD
Name: DISTRICT, Length: 640, dtype: object

In [30]:
type(df2['DISTRICT']) # Columns are in Dataframes are type Pandas Series

pandas.core.series.Series

In [36]:
# If we want to restrict certain columns or to get only certain columns use below command
df2[['DISTRICT','OCT']]

           DISTRICT    OCT
0           NICOBAR  326.0
1     SOUTH ANDAMAN  301.2
2     N & M ANDAMAN  276.1
3             LOHIT  167.1
4        EAST SIANG  206.9
5     SUBANSIRI F.D   75.9
6             TIRAP  218.7
7     ANJAW (LOHIT)  167.1
8      LOWER DIBANG  167.2
9         CHANGLANG  275.0
10       PAPUM PARE  214.7
11    LOW SUBANSIRI   78.5
12      UPPER SIANG  264.9
13       WEST SIANG  126.8
14    DIBANG VALLEY  167.2
15      WEST KAMENG  233.9
16      EAST KAMENG  138.2
17    TAWANG(W KAME  233.9
18     KURUNG KUMEY   92.3
19           CACHAR  182.4
20          DARRANG   95.4
21         GOALPARA  157.7
22           KAMRUP  106.6
23        LAKHIMPUR  140.3
24     NORTH CACHAR  196.4
25           NAGAON  120.0
26        SIVASAGAR   96.3
27          BARPETA  142.1
28           DHUBRI  155.1
29        DIBRUGARH  136.9
..              ...    ...
610   BANGALORE RUR  171.8
611         BELLARY  116.3
612     CHIKMAGALUR  167.4
613     CHITRADURGA  116.4
614          KODAGU  201.7
615          HASSAN  156.0
616           KOLAR  148.2
617          MANDYA  153.1
618          MYSORE  152.4
619         SHIMOGA  137.5
620          TUMKUR  148.9
621   BANGALORE URB  159.7
622   CHAMARAJANAGA  157.8
623       DAVANGERE  124.4
624  RAMNAGAR(BNGR)  174.1
625   CHICKBALLAPUR  156.8
626       ALAPPUZHA  332.9
627          CANNUR  229.4
628       ERNAKULAM  299.9
629        KOTTAYAM  316.6
630       KOZHIKODE  262.1
631      MALAPPURAM  290.4
632        PALAKKAD  263.8
633          KOLLAM  362.7
634        THRISSUR  296.3
635   THIRUVANANTHA  268.0
636          IDUKKI  343.2
637        KASARGOD  234.9
638  PATHANAMTHITTA  359.4
639         WAYANAD  213.1

[640 rows x 2 columns]

In [32]:
#If we want to find the maximum & Minimum values in any column data use following command
df2['OCT'].max()
df2['OCT'].min()

3.1

In [33]:
#If we want get statistical Data use following command
df2.describe()

,JAN,FEB,MAR,APR,MAY,JUN,JUL,AUG,SEP,OCT,NOV,DEC,ANNUAL,JAN+FEB,MAM,JJAS,OND
count,640.000000,640.000000,640.000000,640.000000,640.000000,640.000000,640.000000,640.000000,640.000000,640.000000,640.000000,640.000000,640.000000,640.000000,640.000000,640.000000,640.000000
mean,18.351250,20.994219,30.063281,45.537969,81.394219,195.797656,326.093594,291.267344,194.658281,90.342188,33.986875,18.087344,1346.574219,39.345469,156.995469,1007.816875,142.416406
std,21.099075,27.750169,45.480904,71.612125,111.991086,196.638268,221.532589,152.738890,99.900836,75.002933,59.325498,32.697014,839.475249,47.249457,213.592042,629.824745,148.876573
min,0.000000,0.000000,0.000000,0.000000,0.900000,3.800000,11.600000,14.100000,8.600000,3.100000,1.200000,0.000000,94.600000,0.000000,1.500000,39.600000,5.600000
25%,6.875000,7.000000,7.000000,5.000000,12.100000,68.775000,206.375000,194.500000,128.800000,34.275000,6.600000,5.300000,830.200000,14.650000,27.775000,624.900000,51.575000
50%,13.300000,12.300000,12.700000,15.050000,33.850000,131.700000,293.900000,284.950000,181.400000,62.500000,12.900000,7.900000,1115.100000,27.700000,67.200000,894.350000,86.550000
75%,19.125000,24.100000,33.275000,48.075000,91.825000,226.225000,374.800000,358.300000,234.175000,130.200000,32.150000,14.825000,1528.875000,41.100000,171.200000,1194.125000,174.900000
max,144.500000,229.600000,367.900000,554.400000,733.700000,1476.200000,1820.900000,1522.100000,826.300000,517.700000,475.100000,297.700000,7229.300000,335.300000,1256.500000,5228.000000,1048.500000

In [34]:
df2

,STATE/UT,DISTRICT,JAN,FEB,MAR,APR,MAY,JUN,JUL,AUG,SEP,OCT,NOV,DEC,ANNUAL,JAN+FEB,MAM,JJAS,OND
0,ANDAMAN And NICOBAR ISLANDS,NICOBAR,107.3,57.9,65.2,117.0,358.5,295.5,285.0,271.9,354.8,326.0,315.2,250.9,2805.2,165.2,540.7,1207.2,892.1
1,ANDAMAN And NICOBAR ISLANDS,SOUTH ANDAMAN,43.7,26.0,18.6,90.5,374.4,457.2,421.3,423.1,455.6,301.2,275.8,128.3,3015.7,69.7,483.5,1757.2,705.3
2,ANDAMAN And NICOBAR ISLANDS,N & M ANDAMAN,32.7,15.9,8.6,53.4,343.6,503.3,465.4,460.9,454.8,276.1,198.6,100.0,2913.3,48.6,405.6,1884.4,574.7
3,ARUNACHAL PRADESH,LOHIT,42.2,80.8,176.4,358.5,306.4,447.0,660.1,427.8,313.6,167.1,34.1,29.8,3043.8,123.0,841.3,1848.5,231.0
4,ARUNACHAL PRADESH,EAST SIANG,33.3,79.5,105.9,216.5,323.0,738.3,990.9,711.2,568.0,206.9,29.5,31.7,4034.7,112.8,645.4,3008.4,268.1
5,ARUNACHAL PRADESH,SUBANSIRI F.D,28.0,48.3,85.3,101.5,140.5,228.4,217.4,182.8,159.8,75.9,20.9,11.6,1300.4,76.3,327.3,788.4,108.4
6,ARUNACHAL PRADESH,TIRAP,42.2,72.7,141.0,316.9,328.7,614.7,851.9,500.6,418.3,218.7,42.9,22.9,3571.5,114.9,786.6,2385.5,284.5
7,ARUNACHAL PRADESH,ANJAW (LOHIT),42.2,80.8,176.4,358.5,306.4,447.0,660.1,427.8,313.6,167.1,34.1,29.8,3043.8,123.0,841.3,1848.5,231.0
8,ARUNACHAL PRADESH,LOWER DIBANG,83.7,153.9,303.5,383.6,268.0,374.2,272.0,160.5,266.7,167.2,64.0,56.0,2553.3,237.6,955.1,1073.4,287.2
9,ARUNACHAL PRADESH,CHANGLANG,70.3,170.9,367.9,554.4,334.2,526.2,460.8,291.5,353.6,275.0,64.9,74.2,3543.9,241.2,1256.5,1632.1,414.1
10,ARUNACHAL PRADESH,PAPUM PARE,33.5,67.8,106.1,226.9,453.0,640.5,609.5,503.4,492.3,214.7,19.2,11.3,3378.2,101.3,786.0,2245.7,245.2
11,ARUNACHAL PRADESH,LOW SUBANSIRI,97.5,109.3,92.4,204.3,266.2,284.1,248.9,270.5,192.7,78.5,49.5,27.2,1921.1,206.8,562.9,996.2,155.2
12,ARUNACHAL PRADESH,UPPER SIANG,74.3,176.7,362.6,397.5,408.7,801.9,653.0,417.9,686.0,264.9,86.9,71.7,4402.1,251.0,1168.8,2558.8,423.5
13,ARUNACHAL PRADESH,WEST SIANG,26.0,66.7,76.8,229.2,239.5,416.6,592.4,312.4,291.1,126.8,33.7,29.5,2440.7,92.7,545.5,1612.5,190.0
14,ARUNACHAL PRADESH,DIBANG VALLEY,83.7,153.9,303.5,383.6,268.0,374.2,272.0,160.5,266.7,167.2,64.0,56.0,2553.3,237.6,955.1,1073.4,287.2
15,ARUNACHAL PRADESH,WEST KAMENG,35.2,43.5,58.9,134.3,341.1,665.3,749.9,579.1,490.9,233.9,40.3,27.0,3399.4,78.7,534.3,2485.2,301.2
16,ARUNACHAL PRADESH,EAST KAMENG,49.0,74.4,96.5,156.9,208.0,345.7,368.5,256.2,275.9,138.2,34.4,27.2,2030.9,123.4,461.4,1246.3,199.8
17,ARUNACHAL PRADESH,TAWANG(W KAME,35.2,43.5,58.9,134.3,341.1,665.3,749.9,579.1,490.9,233.9,40.3,27.0,3399.4,78.7,534.3,2485.2,301.2
18,ARUNACHAL PRADESH,KURUNG KUMEY,82.7,70.0,128.2,245.7,271.4,292.7,404.0,276.3,283.5,92.3,32.3,42.4,2221.5,152.7,645.3,1256.5,167.0
19,ASSAM,CACHAR,13.3,50.2,168.3,262.5,386.4,532.1,526.2,470.8,360.8,182.4,34.8,11.4,2999.2,63.5,817.2,1889.9,228.6
20,ASSAM,DARRANG,13.1,21.4,53.5,168.8,320.0,419.7,345.8,272.1,221.5,95.4,17.2,9.3,1957.8,34.5,542.3,1259.1,121.9
21,ASSAM,GOALPARA,12.7,20.4,51.1,196.6,399.8,567.8,502.8,334.6,304.9,157.7,21.7,5.2,2575.3,33.1,647.5,1710.1,184.6
22,ASSAM,KAMRUP,12.0,20.8,58.6,151.7,293.4,365.5,345.1,248.7,188.4,106.6,15.1,7.5,1813.4,32.8,503.7,1147.7,129.2
23,ASSAM,LAKHIMPUR,27.7,48.6,76.7,165.5,331.9,528.3,605.2,467.6,424.1,140.3,23.0,20.4,2859.3,76.3,574.1,2025.2,183.7
24,ASSAM,NORTH CACHAR,16.7,47.5,158.9,207.9,308.0,328.1,270.3,201.3,189.1,196.4,42.1,11.2,1977.5,64.2,674.8,988.8,249.7
25,ASSAM,NAGAON,12.0,22.5,48.1,128.9,171.3,285.9,326.3,294.1,218.6,120.0,21.6,10.8,1660.1,34.5,348.3,1124.9,152.4
26,ASSAM,SIVASAGAR,20.1,33.2,78.3,126.5,257.1,255.5,374.8,342.3,196.9,96.3,20.3,10.3,1811.6,53.3,461.9,1169.5,126.9
27,ASSAM,BARPETA,10.3,26.9,54.0,175.7,391.5,694.3,757.3,527.3,462.1,142.1,20.4,12.7,3274.6,37.2,621.2,2441.0,175.2
28,ASSAM,DHUBRI,10.3,11.7,46.6,147.5,391.6,603.0,554.7,418.7,340.1,155.1,19.2,4.1,2702.6,22.0,585.7,1916.5,178.4
29,ASSAM,DIBRUGARH,30.6,53.1,119.8,229.9,292.4,401.0,519.4,405.1,325.9,136.9,24.0,18.5,2556.6,83.7,642.1,1651.4,179.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
610,KARNATAKA,BANGALORE RUR,1.7,5.8,7.6,36.2,93.1,71.2,91.7,118.1,170.9,171.8,55.4,13.5,837.0,7.5,136.9,451.9,240.7
611,KARNATAKA,BELLARY,1.4,1.4,2.9,26.2,57.9,72.4,77.0,89.3,137.3,116.3,31.1,9.6,622.8,2.8,87.0,376.0,157.0
612,KARNATAKA,CHIKMAGALUR,1.6,2.0,12.0,60.2,105.9,395.0,662.1,425.0,175.2,167.4,58.8,12.3,2077.5,3.6,178.1,1657.3,238.5
613,KARNATAKA,CHITRADURGA,1.4,1.2,4.4,25.8,64.9,50.5,56.1,58.9,105.5,116.4,33.8,8.8,527.7,2.6,95.1,271.0,159.0
614,KARNATAKA,KODAGU,3.5,4.2,18.5,89.8,152.7,542.2,884.4,543.9,211.4,201.7,71.6,17.5,2741.4,7.7,261.0,2181.9,290.8
615,KARNATAKA,HASSAN,1.3,2.5,10.7,55.1,102.2,125.0,203.8,130.0,115.5,156.0,54.1,10.9,967.1,3.8,168.0,574.3,221.0
616,KARNATAKA,KOLAR,2.7,4.5,10.4,27.8,74.4,63.3,76.4,91.2,151.8,148.2,58.8,21.6,731.1,7.2,112.6,382.7,228.6
617,KARNATAKA,MANDYA,1.9,3.6,7.6,45.3,105.1,48.7,49.3,58.9,128.2,153.1,47.0,14.0,662.7,5.5,158.0,285.1,214.1
618,KARNATAKA,MYSORE,2.5,3.5,11.4,58.7,124.6,79.7,92.4,64.8,106.7,152.4,48.8,13.1,758.6,6.0,194.7,343.6,214.3
619,KARNATAKA,SHIMOGA,0.5,0.4,6.3,38.0,78.3,346.8,624.3,403.8,139.1,137.5,44.6,8.3,1827.9,0.9,122.6,1514.0,190.4
620,KARNATAKA,TUMKUR,2.4,3.0,7.1,34.0,87.1,61.5,69.7,79.5,148.5,148.9,46.7,10.1,698.5,5.4,128.2,359.2,205.7
621,KARNATAKA,BANGALORE URB,2.3,6.7,8.2,39.2,106.3,73.9,91.6,128.9,181.3,159.7,53.9,18.0,870.0,9.0,153.7,475.7,231.6
622,KARNATAKA,CHAMARAJANAGA,3.4,6.0,13.2,69.2,131.2,61.8,68.7,66.0,124.1,157.8,62.7,24.3,788.4,9.4,213.6,320.6,244.8
623,KARNATAKA,DAVANGERE,1.1,0.8,4.2,35.0,74.0,78.7,102.9,87.0,116.3,124.4,44.9,7.4,676.7,1.9,113.2,384.9,176.7
624,KARNATAKA,RAMNAGAR(BNGR),1.5,4.7,10.2,47.9,122.3,73.1,84.5,108.8,187.6,174.1,54.0,15.0,883.7,6.2,180.4,454.0,243.1
625,KARNATAKA,CHICKBALLAPUR,2.1,4.6,8.2,27.2,69.4,64.3,89.2,104.9,153.4,156.8,52.9,15.5,748.5,6.7,104.8,411.8,225.2
626,KERALA,ALAPPUZHA,17.5,27.9,45.1,134.0,298.7,593.0,533.0,343.1,276.8,332.9,187.6,51.6,2841.2,45.4,477.8,1745.9,572.1
627,KERALA,CANNUR,2.5,2.0,7.6,57.9,235.0,852.4,1055.0,540.9,220.7,229.4,91.6,24.1,3319.1,4.5,300.5,2669.0,345.1
628,KERALA,ERNAKULAM,13.2,18.8,31.2,112.0,300.4,696.4,670.2,401.3,297.1,299.9,145.0,44.4,3029.9,32.0,443.6,2065.0,489.3
629,KERALA,KOTTAYAM,13.0,24.9,42.3,136.1,281.8,649.1,591.4,386.0,270.8,316.6,177.4,41.1,2930.5,37.9,460.2,1897.3,535.1
630,KERALA,KOZHIKODE,2.3,3.9,15.1,80.9,256.6,895.8,955.2,500.9,251.2,262.1,130.1,30.0,3384.1,6.2,352.6,2603.1,422.2
631,KERALA,MALAPPURAM,1.7,3.9,12.7,86.8,221.3,660.9,792.9,395.3,211.3,290.4,135.1,22.8,2835.1,5.6,320.8,2060.4,448.3
632,KERALA,PALAKKAD,2.9,6.5,22.5,98.7,158.7,464.3,595.4,333.8,179.2,263.8,138.6,25.6,2290.0,9.4,279.9,1572.7,428.0
633,KERALA,KOLLAM,17.5,33.7,62.6,158.5,248.5,457.7,398.0,258.7,217.9,362.7,221.4,54.5,2491.7,51.2,469.6,1332.3,638.6
634,KERALA,THRISSUR,3.4,7.5,17.0,79.2,289.1,707.4,772.9,440.1,277.1,296.3,138.1,35.0,3063.1,10.9,385.3,2197.5,469.4
635,KERALA,THIRUVANANTHA,19.3,21.1,35.5,116.7,216.6,338.7,228.9,142.0,161.7,268.0,192.0,62.7,1803.2,40.4,368.8,871.3,522.7
636,KERALA,IDUKKI,13.4,22.1,43.6,150.4,232.6,651.6,788.9,527.3,308.4,343.2,172.9,48.1,3302.5,35.5,426.6,2276.2,564.2
637,KERALA,KASARGOD,2.3,1.0,8.4,46.9,217.6,999.6,1108.5,636.3,263.1,234.9,84.6,18.4,3621.6,3.3,272.9,3007.5,337.9
638,KERALA,PATHANAMTHITTA,19.8,45.2,73.9,184.9,294.7,556.9,539.9,352.7,266.2,359.4,213.5,51.3,2958.4,65.0,553.5,1715.7,624.2
639,KERALA,WAYANAD,4.8,8.3,17.5,83.3,174.6,698.1,1110.4,592.9,230.7,213.1,93.6,25.8,3253.1,13.1,275.4,2632.1,332.5

In [40]:
# If we want get data in dataframe using condition (This is similar to SQL Query)
df2[df2.OCT>=500]

,STATE/UT,DISTRICT,JAN,FEB,MAR,APR,MAY,JUN,JUL,AUG,SEP,OCT,NOV,DEC,ANNUAL,JAN+FEB,MAM,JJAS,OND
47,MEGHALAYA,JAINTIA HILLS,33.8,44.1,115.1,282.3,598.8,1316.1,1591.3,933.8,826.3,517.7,110.9,9.7,6379.9,77.9,996.2,4667.5,638.3

In [42]:
# If we want to get the complet row of a max value in OCT using condition as follows
df2[df2.OCT==df2.OCT.max()]
#(OR)
df2[df2.OCT==df2['OCT'].max()] # This we'll prefer incase if columns are having any spaces

,STATE/UT,DISTRICT,JAN,FEB,MAR,APR,MAY,JUN,JUL,AUG,SEP,OCT,NOV,DEC,ANNUAL,JAN+FEB,MAM,JJAS,OND
47,MEGHALAYA,JAINTIA HILLS,33.8,44.1,115.1,282.3,598.8,1316.1,1591.3,933.8,826.3,517.7,110.9,9.7,6379.9,77.9,996.2,4667.5,638.3

In [45]:
#If we want to know the state where weather where max rainfall in Oct month
df2[['STATE/UT','DISTRICT']][df2.OCT==df2['OCT'].max()]

     STATE/UT       DISTRICT
47  MEGHALAYA  JAINTIA HILLS

In [46]:
df2.reset_index(inplace=True)

In [48]:
#If we want to know index of DataFrame
df2.index

RangeIndex(start=0, stop=640, step=1)

In [49]:
#If we want to set any particular column as index do as below
df2.set_index('STATE/UT', inplace=True)

In [50]:
df2.loc['KERALA']

,index,DISTRICT,JAN,FEB,MAR,APR,MAY,JUN,JUL,AUG,SEP,OCT,NOV,DEC,ANNUAL,JAN+FEB,MAM,JJAS,OND
STATE/UT,,,,,,,,,,,,,,,,,,,
KERALA,626,ALAPPUZHA,17.5,27.9,45.1,134.0,298.7,593.0,533.0,343.1,276.8,332.9,187.6,51.6,2841.2,45.4,477.8,1745.9,572.1
KERALA,627,CANNUR,2.5,2.0,7.6,57.9,235.0,852.4,1055.0,540.9,220.7,229.4,91.6,24.1,3319.1,4.5,300.5,2669.0,345.1
KERALA,628,ERNAKULAM,13.2,18.8,31.2,112.0,300.4,696.4,670.2,401.3,297.1,299.9,145.0,44.4,3029.9,32.0,443.6,2065.0,489.3
KERALA,629,KOTTAYAM,13.0,24.9,42.3,136.1,281.8,649.1,591.4,386.0,270.8,316.6,177.4,41.1,2930.5,37.9,460.2,1897.3,535.1
KERALA,630,KOZHIKODE,2.3,3.9,15.1,80.9,256.6,895.8,955.2,500.9,251.2,262.1,130.1,30.0,3384.1,6.2,352.6,2603.1,422.2
KERALA,631,MALAPPURAM,1.7,3.9,12.7,86.8,221.3,660.9,792.9,395.3,211.3,290.4,135.1,22.8,2835.1,5.6,320.8,2060.4,448.3
KERALA,632,PALAKKAD,2.9,6.5,22.5,98.7,158.7,464.3,595.4,333.8,179.2,263.8,138.6,25.6,2290.0,9.4,279.9,1572.7,428.0
KERALA,633,KOLLAM,17.5,33.7,62.6,158.5,248.5,457.7,398.0,258.7,217.9,362.7,221.4,54.5,2491.7,51.2,469.6,1332.3,638.6
KERALA,634,THRISSUR,3.4,7.5,17.0,79.2,289.1,707.4,772.9,440.1,277.1,296.3,138.1,35.0,3063.1,10.9,385.3,2197.5,469.4
KERALA,635,THIRUVANANTHA,19.3,21.1,35.5,116.7,216.6,338.7,228.9,142.0,161.7,268.0,192.0,62.7,1803.2,40.4,368.8,871.3,522.7
KERALA,636,IDUKKI,13.4,22.1,43.6,150.4,232.6,651.6,788.9,527.3,308.4,343.2,172.9,48.1,3302.5,35.5,426.6,2276.2,564.2
KERALA,637,KASARGOD,2.3,1.0,8.4,46.9,217.6,999.6,1108.5,636.3,263.1,234.9,84.6,18.4,3621.6,3.3,272.9,3007.5,337.9
KERALA,638,PATHANAMTHITTA,19.8,45.2,73.9,184.9,294.7,556.9,539.9,352.7,266.2,359.4,213.5,51.3,2958.4,65.0,553.5,1715.7,624.2
KERALA,639,WAYANAD,4.8,8.3,17.5,83.3,174.6,698.1,1110.4,592.9,230.7,213.1,93.6,25.8,3253.1,13.1,275.4,2632.1,332.5